#Write a program to perform different Arithmetic Operations on numbers in Python.

a=int(input("Enter the value of a:"))            #take value a and b from user
b=int(input("Enter the value of b:"))
#perform all Arithmetic Operation and print it
print("The Addition of ",a,"and",b,"is",a+b)     
print("The Substraction of ",a,"and",b,"is",a-b)         
print("The Multiplication of ",a,"and",b,"is",a*b)       
print("The Division of ",a,"and",b,"is",a/b)
print("The Modulus of ",a,"and",b,"is",a%b)
print("The Exponentiation of ",a,"and",b,"is",a**b)
print("The Floor division of ",a,"and",b,"is",a//b)